global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'agricultural-iot-rag'
    static_configs:
      - targets: ['172.17.0.1:8081']
        labels:
          service: 'api'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
